

const cards = [
    // spades
    { id: 1, cardName: "s2",value:6 },
    { id: 2, cardName: "s3",value:7 },
    { id: 3, cardName: "s4",value:8 },
    { id: 4, cardName: "s5",value:9 },
    { id: 5, cardName: "s6",value:10 },
    { id: 6, cardName: "s7",value:11 },
    { id: 7, cardName: "s8",value:12 },
    { id: 8, cardName: "s9",value:13 },
    { id: 9, cardName: "s10",value:14 },
    { id: 10, cardName: "sJ",value:15 },
    { id: 11, cardName: "sQ",value:16 },
    { id: 12, cardName: "sK",value:17},
    { id: 13, cardName: "sA",value:18 },
    // hearts
    { id: 14, cardName: "h2",value:5 },
    { id: 15, cardName: "h3",value:6 },
    { id: 16, cardName: "h4",value:7 },
    { id: 17, cardName: "h5",value:8 },
    { id: 18, cardName: "h6",value:9 },
    { id: 19, cardName: "h7",value:10 },
    { id: 20, cardName: "h8",value:11 },
    { id: 21, cardName: "h9",value:12 },
    { id: 22, cardName: "h10",value:13 },
    { id: 23, cardName: "hJ",value:14 },
    { id: 24, cardName: "hQ",value:15 },
    { id: 25, cardName: "hK",value:16 },
    { id: 26, cardName: "hA",value:17 },
    // clubs
    { id: 27, cardName: "c2",value:4 },
    { id: 28, cardName: "c3",value:5 },
    { id: 29, cardName: "c4",value:6 },
    { id: 30, cardName: "c5",value:7 },
    { id: 31, cardName: "c6",value:8 },
    { id: 32, cardName: "c7",value:9 },
    { id: 33, cardName: "c8",value:10 },
    { id: 34, cardName: "c9",value:11 },
    { id: 35, cardName: "c10",value:12 },
    { id: 36, cardName: "cJ",value:13 },
    { id: 37, cardName: "cQ",value:14 },
    { id: 38, cardName: "cK",value:15 },
    { id: 39, cardName: "cA",value:16 },
    // diamonds
    { id: 40, cardName: "d2",value:3 },
    { id: 41, cardName: "d3",value:4 },
    { id: 42, cardName: "d4",value:5 },
    { id: 43, cardName: "d5",value:6 },
    { id: 44, cardName: "d6",value:7 },
    { id: 45, cardName: "d7",value:8 },
    { id: 46, cardName: "d8",value:9 },
    { id: 47, cardName: "d9",value:10 },
    { id: 48, cardName: "d10",value:11 },
    { id: 49, cardName: "dJ",value:12 },
    { id: 50, cardName: "dQ",value:13 },
    { id: 51, cardName: "dK",value:14 },
    { id: 52, cardName: "dA",value:15 },
];

module.exports = cards;
