const cards = [
    // spades
    { id: 1, cardName: "s2" },
    { id: 2, cardName: "s3" },
    { id: 3, cardName: "s4" },
    { id: 4, cardName: "s5" },
    { id: 5, cardName: "s6" },
    { id: 6, cardName: "s7" },
    { id: 7, cardName: "s8" },
    { id: 8, cardName: "s9" },
    { id: 9, cardName: "s10" },
    { id: 10, cardName: "sJ" },
    { id: 11, cardName: "sQ" },
    { id: 12, cardName: "sK" },
    { id: 13, cardName: "sA" },
    // hearts
    { id: 14, cardName: "h2" },
    { id: 15, cardName: "h3" },
    { id: 16, cardName: "h4" },
    { id: 17, cardName: "h5" },
    { id: 18, cardName: "h6" },
    { id: 19, cardName: "h7" },
    { id: 20, cardName: "h8" },
    { id: 21, cardName: "h9" },
    { id: 22, cardName: "h10" },
    { id: 23, cardName: "hJ" },
    { id: 24, cardName: "hQ" },
    { id: 25, cardName: "hK" },
    { id: 26, cardName: "hA" },
    // clubs
    { id: 27, cardName: "c2" },
    { id: 28, cardName: "c3" },
    { id: 29, cardName: "c4" },
    { id: 30, cardName: "c5" },
    { id: 31, cardName: "c6" },
    { id: 32, cardName: "c7" },
    { id: 33, cardName: "c8" },
    { id: 34, cardName: "c9" },
    { id: 35, cardName: "c10" },
    { id: 36, cardName: "cJ" },
    { id: 37, cardName: "cQ" },
    { id: 38, cardName: "cK" },
    { id: 39, cardName: "cA" },
    // diamonds
    { id: 40, cardName: "d2" },
    { id: 41, cardName: "d3" },
    { id: 42, cardName: "d4" },
    { id: 43, cardName: "d5" },
    { id: 44, cardName: "d6" },
    { id: 45, cardName: "d7" },
    { id: 46, cardName: "d8" },
    { id: 47, cardName: "d9" },
    { id: 48, cardName: "d10" },
    { id: 49, cardName: "dJ" },
    { id: 50, cardName: "dQ" },
    { id: 51, cardName: "dK" },
    { id: 52, cardName: "dA" },
];

module.exports = cards;
